import type { CustomizableBase, Product } from "@/lib/types";

export const CATEGORIES = [
  { slug: "todos", name: "Todos" },
  { slug: "camisetas", name: "Camisetas" },
  { slug: "polerones", name: "Polerones" },
  { slug: "tazas", name: "Tazas" },
  { slug: "bolsos", name: "Bolsos" },
  { slug: "gorras", name: "Gorras" },
] as const;

export const PRODUCTS: Product[] = [
  {
    id: "prod-sakura-night",
    slug: "camiseta-sakura-night",
    name: "Camiseta Sakura Night",
    description:
      "Estampado floral sobre negro. Sublimación de alta definición, tela 100% poliéster premium.",
    price: 18990,
    category: "camisetas",
    kind: "shirt",
    design: "sakura",
    colors: ["#111111"],
    sizes: ["S", "M", "L", "XL"],
    featured: true,
  },
  {
    id: "prod-koinu-club",
    slug: "poleron-koinu-club",
    name: "Polerón Koinu Club",
    description:
      "Polerón oversized con estampado club. Interior frisa, print duradero al lavado.",
    price: 34990,
    category: "polerones",
    kind: "hoodie",
    design: "koinu",
    colors: ["#1F2937"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    featured: true,
  },
  {
    id: "prod-buenos-dias",
    slug: "taza-buenos-dias",
    name: "Taza Buenos días, jefe",
    description:
      "Taza cerámica 11 oz con sublimación envolvente. Apta microondas (no lavavajillas agresivo).",
    price: 8990,
    category: "tazas",
    kind: "mug",
    design: "buenos-dias",
    colors: ["#FFFFFF"],
    sizes: [],
    featured: true,
  },
  {
    id: "prod-mercado",
    slug: "tote-mercado-vintage",
    name: "Tote Mercado Vintage",
    description:
      "Bolso de lona gruesa con estampado vintage. Ideal para feria, estudio o día a día.",
    price: 12990,
    category: "bolsos",
    kind: "tote",
    design: "mercado",
    colors: ["#F5E6C8"],
    sizes: [],
    featured: true,
  },
  {
    id: "prod-studio",
    slug: "gorra-studio-print",
    name: "Gorra Studio Print",
    description:
      "Gorra trucker con parche/estampado del taller. Ajuste snapback.",
    price: 11990,
    category: "gorras",
    kind: "cap",
    design: "studio",
    colors: ["#0F766E"],
    sizes: ["Única"],
    featured: false,
  },
  {
    id: "prod-pixel-pup",
    slug: "camiseta-pixel-pup",
    name: "Camiseta Pixel Pup",
    description:
      "Ilustración pixel del perrito Koinu. Colores vivos, cuello reforzado.",
    price: 17990,
    category: "camisetas",
    kind: "shirt",
    design: "pixel",
    colors: ["#F4E1C1"],
    sizes: ["S", "M", "L", "XL"],
    featured: true,
  },
  {
    id: "prod-cafe",
    slug: "taza-cafe-plotter",
    name: "Taza Café & Plotter",
    description: "Homenaje al taller: café, plotter y deadline. Sublimación full wrap.",
    price: 8490,
    category: "tazas",
    kind: "mug",
    design: "cafe",
    colors: ["#FFFFFF"],
    sizes: [],
    featured: false,
  },
  {
    id: "prod-overprint",
    slug: "poleron-overprint",
    name: "Polerón Overprint",
    description:
      "Tipografía grande estilo taller de serigrafía. Corte boxed, felpa suave.",
    price: 32990,
    category: "polerones",
    kind: "hoodie",
    design: "overprint",
    colors: ["#7F1D1D"],
    sizes: ["M", "L", "XL", "XXL"],
    featured: false,
  },
  {
    id: "prod-ruta",
    slug: "camiseta-ruta-nocturna",
    name: "Camiseta Ruta Nocturna",
    description: "Gráfico de carretera y neón. Pensada para salir y verse.",
    price: 19990,
    category: "camisetas",
    kind: "shirt",
    design: "ruta",
    colors: ["#0B1220"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    featured: false,
  },
  {
    id: "prod-tote-koinu",
    slug: "tote-koinu",
    name: "Tote Koinu",
    description: "El isotipo del taller a gran escala. Lona resistente de 12 oz.",
    price: 11990,
    category: "bolsos",
    kind: "tote",
    design: "koinu",
    colors: ["#FFFFFF"],
    sizes: [],
    featured: false,
  },
  {
    id: "prod-flash",
    slug: "gorra-flash-print",
    name: "Gorra Flash Print",
    description: "Frente estampado con rayo de taller. Visera curva.",
    price: 10990,
    category: "gorras",
    kind: "cap",
    design: "flash",
    colors: ["#1A1A1A"],
    sizes: ["Única"],
    featured: true,
  },
  {
    id: "prod-team",
    slug: "taza-team-koinu",
    name: "Taza Team Koinu",
    description: "Para el equipo, clientes y quien viva en el taller.",
    price: 7990,
    category: "tazas",
    kind: "mug",
    design: "team",
    colors: ["#FFFFFF"],
    sizes: [],
    featured: false,
  },
];

export const CUSTOMIZABLE_BASES: CustomizableBase[] = [
  {
    slug: "shirt",
    name: "Camiseta",
    description: "Poliéster premium, ideal para sublimación full print o pecho.",
    basePrice: 18990,
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [
      { name: "Blanco", hex: "#F7F4EF" },
      { name: "Negro", hex: "#171411" },
      { name: "Rosa", hex: "#F9A8D4" },
      { name: "Celeste", hex: "#7DD3FC" },
      { name: "Menta", hex: "#6EE7B7" },
      { name: "Mostaza", hex: "#EAB308" },
    ],
  },
  {
    slug: "hoodie",
    name: "Polerón",
    description: "Polerón con capucha, interior frisa. Estampa grande, pecho o perfiles.",
    basePrice: 34990,
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [
      { name: "Crema", hex: "#F5E6C8" },
      { name: "Gris", hex: "#4B5563" },
      { name: "Negro", hex: "#171411" },
      { name: "Bordo", hex: "#7F1D1D" },
      { name: "Azul noche", hex: "#1E3A5F" },
    ],
  },
  {
    slug: "mug",
    name: "Taza",
    description: "Cerámica 11 oz. Sublimación envolvente o frente.",
    basePrice: 8990,
    sizes: [],
    colors: [
      { name: "Blanco", hex: "#FFFFFF" },
      { name: "Negro", hex: "#171411" },
      { name: "Rosa", hex: "#F9A8D4" },
      { name: "Celeste", hex: "#7DD3FC" },
      { name: "Menta", hex: "#6EE7B7" },
      { name: "Mostaza", hex: "#EAB308" },
    ],
  },
  {
    slug: "tote",
    name: "Tote bag",
    description: "Lona de algodón/poly. Estampa grande al frente.",
    basePrice: 12990,
    sizes: [],
    colors: [
      { name: "Natural", hex: "#F5E6C8" },
      { name: "Blanco", hex: "#FFFFFF" },
      { name: "Negro", hex: "#1F1A17" },
      { name: "Rosa", hex: "#F9A8D4" },
      { name: "Celeste", hex: "#7DD3FC" },
      { name: "Menta", hex: "#6EE7B7" },
    ],
  },
  {
    slug: "cap",
    name: "Gorra",
    description: "Trucker o closed-back. Frente listo para estampar.",
    basePrice: 11990,
    sizes: ["Única"],
    colors: [
      { name: "Negro", hex: "#171411" },
      { name: "Blanco", hex: "#F8FAFC" },
      { name: "Rosa", hex: "#FB7185" },
      { name: "Celeste", hex: "#7DD3FC" },
      { name: "Menta", hex: "#6EE7B7" },
      { name: "Teal", hex: "#0F766E" },
    ],
  },
];

export function getProductBySlug(slug: string) {
  return PRODUCTS.find((product) => product.slug === slug);
}

export function getBaseBySlug(slug: string) {
  return CUSTOMIZABLE_BASES.find((base) => base.slug === slug);
}
